# Tag
TAG_NAME_MAX_LEN = 32
TAG_SLUG_MAX_LEN = 32

# Ingredient
INGREDIENT_NAME_MAX_LEN = 128
INGREDIENT_MEASUREMENT_UNIT_MAX_LEN = 64

# Recipe
RECIPE_NAME_MAX_LEN = 256
MIN_COOKING_TIME = 1
MIN_INGREDIENT_AMOUNT = 1

# User
USER_EMAIL_MAX_LEN = 254

# pagination
MAX_PAGE_SIZE = 100
