# Tag
TAG_NAME_MAX_LEN = 50
TAG_SLUG_MAX_LEN = 50

# Ingredient
INGREDIENT_NAME_MAX_LEN = 50
INGREDIENT_MEASUREMENT_UNIT_MAX_LEN = 50

# Recipe
RECIPE_NAME_MAX_LEN = 100
MIN_COOKING_TIME = 1
MIN_INGREDIENT_AMOUNT = 1

# User
USER_EMAIL_MAX_LEN = 100
