[mypy]
plugins = mypy_django_plugin.main
disallow_untyped_defs = True
warn_return_any = True

[mypy.plugins.django-stubs]
django_settings_module = foodgram_backend.settings

[mypy-foodgram_backend.urls]
disable_error_code = operator,arg-type
