[mypy]
plugins = mypy_django_plugin.main
django_settings_module = foodgram_backend.settings
disallow_untyped_defs = True
warn_return_any = True
; ignore_errors = True

[mypy-foodgram_backend.urls]
disable_error_code = operator, arg-type

[mypy-*.*]
disable_error_code = no-untyped-def, return-value, attr-defined, no-any-return
